version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Set License
          command: |
            mkdir -p $ANDROID_HOME/licenses
            echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
            echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Decrypt signature
          command: |
            openssl aes-256-cbc -d -k $SIGNATURE_DECRYPT_KEY -in signature.tar.gz.enc -out signature.tar.gz
            tar -zxvf signature.tar.gz
            mv google-services.json app/
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Build APK
          command: ./gradlew assembleProductionRelease
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - deploy:
          name: Deploy to DeployGate
          command: |
            [ "$CIRCLE_BRANCH" != "master" ] && exit
            ./gradlew assembleNightlyRelease
            ./deploy.sh
