name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('app/build.gradle') }}
          restore-keys: |
            gradle-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./gradlew androidDependencies
      - name: Decrypt signature
        env:
          SIGNATURE_DECRYPT_KEY: ${{ secrets.SIGNATURE_DECRYPT_KEY }}
        run: |
          set -x
          openssl aes-256-cbc -pbkdf2 -d -k $SIGNATURE_DECRYPT_KEY -in signature.tar.gz.enc -out signature.tar.gz
          tar -xvf signature.tar.gz
      - name: Build with Gradle
        run: ./gradlew buildRelease
